server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git: 
          uri: https://github.com/summerThunder/microservicecloud-config.git
          
          #https://github.com/summerThunder/microservicecloud-config.git
          #git@github.com:summerThunder/microservicecloud-config.git #GitHub上面的git仓库名字
          #username: summerThunder
          #password: qq1678442192 