spring: 
  profiles:
    active:
    - dev
--- 

server:
  port: 8001
spring:
   profiles: dev
   application:
    name: microservicecloud-config-dept-client
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study01
    username: root
    password: qq147258
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml   #可以写成文件也可以直接写出来，直接写出来好内容不多
  type-aliases-package: com.cml.springcloud.entities    #mybatis里还要写出映射实体类的包
  mapper-locations:
  - classpath: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
    cache-enabled: true #开启二级缓存
 
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
 
info:
  app.name: atguigu-microservicecloud-springcloudconfig01
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
 
---

server:
  port: 8001
spring:
   profiles: test
   application:
      name: microservicecloud-config-dept-client
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver             
    url: jdbc:mysql://localhost:3306/study02
    username: root
    password: qq147258
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml   #可以写成文件也可以直接写出来，直接写出来好内容不多
  type-aliases-package: com.cml.springcloud.entities    #mybatis里还要写出映射实体类的包
  mapper-locations:
  - classpath: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
    cache-enabled: true #开启二级缓存
 
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
 
info:
  app.name: atguigu-microservicecloud-springcloudconfig01
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$